name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "ready_for_review"

jobs:
  code-quality:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 7

    env:
      HOME_REPO: /home/repo

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r dev-requirements.txt

      - name: Install library
        run: |
          python -m pip install .

      - name: Ruff
        run: ruff check --output-format=github .

      - name: Mypy
        run: mypy src

      - name: Mdformat
        run: mdformat .

      - name: nbqa
        run: |
          nbqa ruff .
