name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "synchronize"
      - "ready_for_review"

jobs:
  code-quality:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 7

    env:
      HOME_REPO: /home/repo

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r dev-requirements.txt

      - name: Code Quality
        run: |
          isort . -l 120 --check
          black . -l 120 --check
          flake8
          pylint src --rcfile .pylintrc
          pylint tests --rcfile tests/.pylintrc
          mypy src
          bandit -r src -c .bandit
          mdformat .
          nbqa black .
          nbqa isort .
          nbqa flake8 .
          nbqa mypy .
          nbqa mdformat .
